.msfirst

IOCNT0		.equ	0
APORT		.equ	4
ADDR		.equ	5
BPORT		.equ	6
IOCNT1		.equ	16
IOCNT2		.equ	16

R0	.equ	0
R1	.equ	1
R2	.equ	2
R3	.equ	3
R4	.equ	4
R5	.equ	5
R6	.equ	6
R7	.equ	7
R8	.equ	8
R9	.equ	9
R10	.equ	10
R11	.equ	11
R12	.equ	12
R13	.equ	13
R14	.equ	14
R15	.equ	15


P0	.equ	0
P1	.equ	1
P2	.equ	2
P3	.equ	3
P4	.equ	4
P5	.equ	5
P6	.equ	6
P7	.equ	7
P8	.equ	8
P9	.equ	9
P10	.equ	10
P11	.equ	11
P12	.equ	12
P13	.equ	13
P14	.equ	14
P15	.equ	15
P16	.equ	16
P17	.equ	17
P18	.equ	18
P19	.equ	19
P20	.equ	20
P21	.equ	21
P22	.equ	22
P23	.equ	23